### ISSUE TITLE
`SecNonce` should be `Copy`

### ISSUE THREAD

**Issue by storopoli** [conduition/musig2#7]
It is composed of two `Scalar`s

https://github.com/conduition/musig2/blob/98e821c93127583aaba52ec456b393a1ed10c87b/src/nonces.rs#L418-L422

which are `Copy`
https://github.com/conduition/secp/blob/1c225ca916195610659ba12ddedc8da91022044c/src/scalars.rs#L70-L78
.

**Comment by conduition** [comment]
I intentionally chose not to make `SecNonce` copyable to prevent downstream footguns. 

If a secnonce is reused it will leak your private key. To reduce this risk, the `musig2` API encourages callers to consume the `SecNonce` when signing with [`sign_partial`](https://docs.rs/musig2/latest/musig2/fn.sign_partial.html) (functional API). Since `SecNonce` is not `Copy`, the caller would have to invoke `.clone()` or otherwise explicitly duplicate the `SecNonce` for it to be reused. The state machine API with `FirstRound` is even more secure, as the caller never even has access to the `SecNonce` and so it cannot be duplicated in memory at all.

If you _really_ need to represent a secret nonce as a copyable value, you could [serialize it to a `[u8; 64]`](https://docs.rs/musig2/latest/musig2/struct.SecNonce.html#method.serialize), and deserialize before signing. I would urge caution when doing this though.

That said, i'm open to adding `Copy` if you know of a good reason beyond ergonomics.

**Comment by storopoli** [comment]
I see your point. Definitely makes sense.
You can close this :)
